// <auto-generated />
using EntityFramework.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFramework.Migrations
{
    [DbContext(typeof(EntityDBContext))]
    [Migration("20220923234812_ResetDB")]
    partial class ResetDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EntityFramework.Models.DataModels.Libro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Libros");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Autor = "aut1",
                            Titulo = "tit1",
                            UsuarioId = -1
                        },
                        new
                        {
                            Id = -2,
                            Autor = "aut2",
                            Titulo = "tit2",
                            UsuarioId = -1
                        },
                        new
                        {
                            Id = -3,
                            Autor = "aut3",
                            Titulo = "tit3",
                            UsuarioId = -2
                        },
                        new
                        {
                            Id = -4,
                            Autor = "aut4",
                            Titulo = "tit4",
                            UsuarioId = -3
                        },
                        new
                        {
                            Id = -5,
                            Autor = "aut5",
                            Titulo = "tit5",
                            UsuarioId = -3
                        },
                        new
                        {
                            Id = -6,
                            Autor = "aut6",
                            Titulo = "tit6",
                            UsuarioId = -3
                        });
                });

            modelBuilder.Entity("EntityFramework.Models.DataModels.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("LibroId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            LibroId = 0,
                            Nombre = "Usu1"
                        },
                        new
                        {
                            Id = -2,
                            LibroId = 0,
                            Nombre = "Usu2"
                        },
                        new
                        {
                            Id = -3,
                            LibroId = 0,
                            Nombre = "Usu3"
                        });
                });

            modelBuilder.Entity("LibroUsuario", b =>
                {
                    b.Property<int>("LibrosId")
                        .HasColumnType("int");

                    b.Property<int>("UsuariosId")
                        .HasColumnType("int");

                    b.HasKey("LibrosId", "UsuariosId");

                    b.HasIndex("UsuariosId");

                    b.ToTable("LibroUsuario");
                });

            modelBuilder.Entity("LibroUsuario", b =>
                {
                    b.HasOne("EntityFramework.Models.DataModels.Libro", null)
                        .WithMany()
                        .HasForeignKey("LibrosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFramework.Models.DataModels.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
